export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";
export const CLEAR_MESSAGE="CLEAR_MESSAGE";

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";

export const LOGOUT_USER_REQUEST="LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS="LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL="LOGOUT_USER_FAIL";

export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL";


export const CHANGE_PASSWORD_REQUEST="CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL="CHANGE_PASSWORD_FAIL";

export const UPDATE_PROFILE_PICTURE_REQUEST="UPDATE_PROFILE_PICTURE_REQUEST";
export const UPDATE_PROFILE_PICTURE_SUCCESS="UPDATE_PROFILE_PICTURE_SUCCESS";
export const UPDATE_PROFILE_PICTURE_FAIL="UPDATE_PROFILE_PICTURE_FAIL";